### ISSUE TITLE
Build Button with Icon

### ISSUE THREAD

**Issue by slkennedy** [unumux/components#2]
https://paper.dropbox.com/doc/Component-Naming-and-Markup-7uV1uyguRPDqQt3bYPawH#:uid=936531278&h2=🐵-Buttons-with-Icon

**Comment by rebekahpadula** [comment]
Hey testing dis

**Comment by bollinghball** [comment]
Look at the code for this when you get a second!

**Comment by slkennedy** [comment]
Rework button and anchor tag examples to use background images instead of <img>.

**Comment by slkennedy** [comment]
Will need to further review the background image idea. May effect HTML of this component, but since this discussion will come more from the SCSS work related to this component I am closing this issue b/c the initial HTML was completed for R1
