### ISSUE TITLE
Build Footer-Nav

### ISSUE THREAD

**Issue by bollinghball** [unumux/components#8]
## Detailed Description

A longer navigation list that contains the site navigation items as well as extra items. Often used in a site’s footer.
## Context

https://paper.dropbox.com/doc/Component-Standards-and-Markup-7uV1uyguRPDqQt3bYPawH#:uid=352668597879865&h2=%F0%9F%90%B5-Footer-Nav---Addie

**Comment by slkennedy** [comment]
HTML completed with R1
